### ISSUE TITLE
Provide more information on how jumpthegun works in README

### ISSUE THREAD

**Issue by boegel** [taleinat/jumpthegun#2]
As is clear from the replies to [your tweet](https://twitter.com/TalEinat/status/1649149875995439118), you leave people wondering what `jumpthegun` does exactly.

If I would have to guess, I'd say it involves some kind of caching, but I really have no idea without spending a significant amount of time figuring out the code...

How about adding a couple of sentences to explain what `jumpthegun` does into the README?

**Comment by taleinat** [comment]
Great idea, and indeed that was on the top of my to-do list for JumpTheGun. Now done, see the README!
